export const tableRows = [
  {
    id: 1143155,
    product: "Acer Nitro 5",
    customer: "John Smith",
    amount: 785,
    status: "Approved",
  },
  {
    id: 2235235,
    product: "Playstation 5",
    customer: "Michael Doe",
    amount: 900,
    status: "Pending",
  },
  {
    id: 2342353,
    product: "Redragon S101",
    customer: "John Smith",
    amount: 35,
    status: "Pending",
  },
  {
    id: 2357741,
    product: "Razer Blade 15",
    customer: "Jane Smith",
    amount: 920,
    status: "Approved",
  },
  {
    id: 2342355,
    product: "ASUS ROG Strix",
    customer: "Harold Carol",
    amount: 2000,
    status: "Pending",
  },
];

export const dataLineChart = [
  {
    name: "00:00",
    sales: 31,
    revenue: 11,
    costumers: 15,
  },
  {
    name: "00:10",
    sales: 40,
    revenue: 31,
    costumers: 11,
  },
  {
    name: "00:20",
    sales: 28,
    revenue: 45,
    costumers: 32,
  },
  {
    name: "00:30",
    sales: 51,
    revenue: 32,
    costumers: 18,
  },
  {
    name: "00:40",
    sales: 42,
    revenue: 34,
    costumers: 9,
  },
  {
    name: "00:50",
    sales: 82,
    revenue: 52,
    costumers: 25,
  },
  {
    name: "00:60",
    sales: 56,
    revenue: 41,
    costumers: 11,
  },
];

export const userRows = [
  {
    id: 1,
    username: "Snow",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    status: "active",
    email: "1snow@gmail.com",
    age: 35,
  },
  {
    id: 2,
    username: "Jamie Lannister",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "2snow@gmail.com",
    status: "passive",
    age: 42,
  },
  {
    id: 3,
    username: "Lannister",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "3snow@gmail.com",
    status: "pending",
    age: 45,
  },
  {
    id: 4,
    username: "Stark",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "4snow@gmail.com",
    status: "active",
    age: 16,
  },
  {
    id: 5,
    username: "Targaryen",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "5snow@gmail.com",
    status: "passive",
    age: 22,
  },
  {
    id: 6,
    username: "Melisandre",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "6snow@gmail.com",
    status: "active",
    age: 15,
  },
  {
    id: 7,
    username: "Clifford",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "7snow@gmail.com",
    status: "passive",
    age: 44,
  },
  {
    id: 8,
    username: "Frances",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "8snow@gmail.com",
    status: "active",
    age: 36,
  },
  {
    id: 9,
    username: "Roxie",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "snow@gmail.com",
    status: "pending",
    age: 65,
  },
  {
    id: 10,
    username: "Roxie",
    img: "https://images.pexels.com/photos/1820770/pexels-photo-1820770.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    email: "snow@gmail.com",
    status: "active",
    age: 65,
  },
];
